version: "{branch}.build.{build}"
skip_tags: true

branches:
  only:
    - develop

clone_folder:  c:\projects\php_win32ps

install:
  ps: |

    echo "Build cache directory c:\build-cache"
    if (-not (Test-Path c:\build-cache)) {
            mkdir c:\build-cache
    }

    echo "Download PHP 8 binary tools"
    $bname = 'php-sdk-' + $env:BIN_SDK_VER + '.zip'
    if (-not (Test-Path c:\build-cache\$bname)) {
            Invoke-WebRequest "https://github.com/OSTC/php-sdk-binary-tools/archive/$bname" -OutFile "c:\build-cache\$bname"
    }
    $dname0 = 'php-sdk-binary-tools-php-sdk-' + $env:BIN_SDK_VER
    $dname1 = 'php-sdk-' + $env:BIN_SDK_VER
    if (-not (Test-Path c:\build-cache\$dname1)) {
            7z x c:\build-cache\$bname -oc:\build-cache
            # Sleep 5 seconds (process cannot access the file)
            Start-Sleep -s 5
            move c:\build-cache\$dname0 c:\build-cache\$dname1
    }

    echo "Copy GIT files to SRC build directory"
    xcopy c:\projects\php_win32ps C:\projects\php-src\ext\php_win32ps\ /s /e /y /f

cache:
  c:\build-cache -> .appveyor.yml

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
      ARCH: x64
      VC: vs16
      PHP_VER: 8.2.25
      TS: 1

build_script:
  ps: |

    $ts_part = ''
    if ('0' -eq $env:TS) { $ts_part = '-nts' }
    $bname = 'php-devel-pack-' + $env:PHP_VER + $ts_part + '-Win32-' + $env:VC.toUpper() + '-' + $env:ARCH + '.zip'
    echo "Download PHP8 development pack from release http://windows.php.net/downloads/releases/$bname"
    if (-not (Test-Path c:\build-cache\$bname)) {
            Invoke-WebRequest "http://windows.php.net/downloads/releases/$bname" -OutFile "c:\build-cache\$bname"
            if (-not (Test-Path c:\build-cache\$bname)) {
                    Invoke-WebRequest "http://windows.php.net/downloads/releases/$bname" -OutFile "c:\build-cache\$bname"
            }
    }
    
    $dname0 = 'php-' + $env:PHP_VER + '-devel-' + $env:VC.toUpper() + '-' + $env:ARCH
    $dname1 = 'php-' + $env:PHP_VER + $ts_part + '-devel-' + $env:VC.toUpper() + '-' + $env:ARCH
    if (-not (Test-Path c:\build-cache\$dname1)) {
            7z x c:\build-cache\$bname -oc:\build-cache
            # Same directory???
            #echo Moving c:\build-cache\$dname0 to c:\build-cache\$dname1
            #move c:\build-cache\$dname0 c:\build-cache\$dname1
    }

    echo "Main build process..."
    cd c:\projects\php_win32ps
    $env:PATH = 'c:\build-cache\' + $dname1 + ';' + $env:PATH
    echo "" | Out-File -Encoding "ASCII" task.bat
    echo "call phpize 2>&1" | Out-File -Encoding "ASCII" -Append task.bat
    $conf_cmd = 'call configure --enable-win32ps=shared --enable-debug-pack 2>&1'
    echo $conf_cmd | Out-File -Encoding "ASCII" -Append task.bat
    echo "nmake /nologo 2>&1" | Out-File -Encoding "ASCII" -Append task.bat
    echo "exit %errorlevel%" | Out-File -Encoding "ASCII" -Append task.bat
    $here = (Get-Item -Path "." -Verbose).FullName
    $runner = 'c:\build-cache\php-sdk-' + $env:BIN_SDK_VER + '\phpsdk' + '-' + $env:VC + '-' + $env:ARCH + '.bat'
    $task = $here + '\task.bat'
    & $runner -t $task

after_build:
  ps: |

    echo "Build download archive of build extension and save as artifact..."
    $ts_part = 'ts'
    if ('0' -eq $env:TS) { $ts_part = '-nts' }
    $zip_bname = 'php_win32ps-' + $env:APPVEYOR_REPO_COMMIT.substring(0, 8) + '-' + $env:PHP_VER.substring(0, 3) + '-' + $ts_part + '-' + $env:VC + '-' + $env:ARCH + '.zip'
    $dir = 'c:\projects\php_win32ps\';
    if ('x64' -eq $env:ARCH) { $dir = $dir + 'x64\' }
    $dir = $dir + 'Release'
    if ('1' -eq $env:TS) { $dir = $dir + '_TS' }
    & 7z a c:\$zip_bname $dir\php_win32ps.dll
    Push-AppveyorArtifact c:\$zip_bname

test_script:
  ps: |

    echo "Start tests..."
